from django.urls import path

from .views import (
    AboutUsPageView,
    AccountCreateView,
    AccountDeleteView,
    AccountDetailView,
    AccountListView,
    AccountUpdateView,
    ApartmentCreateView,
    ApartmentDeleteView,
    ApartmentDetailView,
    ApartmentListView,
    ApartmentUpdateView,
    CallMasterCreateView,
    CallMasterDeleteView,
    CallMasterDetailView,
    CallMasterListView,
    CallMasterUpdateView,
    CashBoxDeleteView,
    CashBoxExpenseCreateView,
    CashboxExportExcelView,
    CashBoxIncomeCreateView,
    CashBoxListView,
    CashBoxUpdateView,
    ContactPageView,
    CounterReadingCreateView,
    CounterReadingDeleteView,
    CounterReadingDetailView,
    CounterReadingHistoryView,
    CounterReadingUpdateView,
    CreateArticleView,
    DeleteArticleView,
    EditArticleView,
    HouseDeleteView,
    HouseDetailView,
    HouseListView,
    HouseView,
    ListArticleView,
    MainPageView,
    MessageCreateView,
    MessageDeleteView,
    MessageDetailView,
    MessageListView,
    OwnerCreateView,
    OwnerListView,
    PaymentDetailView,
    PersonalAccountExportExcelView,
    ReceiptCopyView,
    ReceiptCreateView,
    ReceiptDeleteView,
    ReceiptDetailView,
    ReceiptListView,
    ReceiptPDFView,
    ReceiptUpdateView,
    RolesUpdateView,
    ServiceEditView,
    ServicePageView,
    StatisticPageView,
    TariffCreateView,
    TariffDetailView,
    TariffListView,
    TariffUpdateView,
    UserCreateView,
    UserDeleteView,
    UserDetailView,
    UserEditView,
    UserListView,
    UserProfileView,
    send_user_invite,
)

app_name = "adminlte"

urlpatterns = [
    path("", StatisticPageView.as_view(), name="statistic"),
    path("managesite/mainpage", MainPageView.as_view(), name="edit_main_page"),
    path("managesite/aboutus", AboutUsPageView.as_view(), name="edit_about_us_page"),
    path("managesite/services", ServicePageView.as_view(), name="edit_service_page"),
    path("managesite/contacts", ContactPageView.as_view(), name="contacts_edit"),
    path("settings/", RolesUpdateView.as_view(), name="roles_update"),
    path("user/edit/<int:pk>", UserEditView.as_view(), name="user_edit"),
    path("user/create/", UserCreateView.as_view(), name="user_create"),
    path("user/list/", UserListView.as_view(), name="users_list"),
    path("user/profile", UserProfileView.as_view(), name="user_profile"),
    path("user/detail/<int:pk>", UserDetailView.as_view(), name="user_detail"),
    path("user/delete/<int:pk>", UserDeleteView.as_view(), name="user_delete"),
    path("service/edit/", ServiceEditView.as_view(), name="service_edit"),
    path("tariff/list/", TariffListView.as_view(), name="tariff_list"),
    path("tariff/detail/<int:pk>", TariffDetailView.as_view(), name="tariff_detail"),
    path("tariffs/create/", TariffCreateView.as_view(), name="tariff_create"),
    path("tariffs/<int:pk>/update/", TariffUpdateView.as_view(), name="tariff_update"),
    path("payment/detail/", PaymentDetailView.as_view(), name="payment_detail"),
    path("article/list/", ListArticleView.as_view(), name="article_list"),
    path("article/edit/<int:pk>", EditArticleView.as_view(), name="article_edit"),
    path("article/create/", CreateArticleView.as_view(), name="article_create"),
    path("article/delete/<int:pk>", DeleteArticleView.as_view(), name="article_delete"),
    path("house/list/", HouseListView.as_view(), name="house_list"),
    path("house/detail/<int:pk>/", HouseDetailView.as_view(), name="house_detail"),
    path("house/create/", HouseView.as_view(), name="house_create"),
    path("house/edit/<int:pk>/", HouseView.as_view(), name="house_update"),
    path("house/delete/<int:pk>/", HouseDeleteView.as_view(), name="house_delete"),
    path("apartment/list/", ApartmentListView.as_view(), name="apartment_list"),
    path("apartment/create/", ApartmentCreateView.as_view(), name="apartment_create"),
    path(
        "aparment/edit/<int:pk>/",
        ApartmentUpdateView.as_view(),
        name="apartment_update",
    ),
    path(
        "apartment/delete/<int:pk>/",
        ApartmentDeleteView.as_view(),
        name="apartment_delete",
    ),
    path(
        "apartment/detail/<int:pk>/",
        ApartmentDetailView.as_view(),
        name="apartment_detail",
    ),
    path("owners/", OwnerListView.as_view(), name="owners_list"),
    path("accounts/create/", AccountCreateView.as_view(), name="account_create"),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path("accounts/<int:pk>/", AccountDetailView.as_view(), name="account_detail"),
    path(
        "accounts/<int:pk>/update/", AccountUpdateView.as_view(), name="account_update"
    ),
    path(
        "accounts/<int:pk>/delete/", AccountDeleteView.as_view(), name="account_delete"
    ),
    path(
        "counter_reading/",
        CounterReadingCreateView.as_view(),
        name="counter_reading_create",
    ),
    path(
        "counter_reading/history/",
        CounterReadingHistoryView.as_view(),
        name="counter_reading_history",
    ),
    path(
        "counter_reading/detail/<int:pk>/",
        CounterReadingDetailView.as_view(),
        name="counter_reading_detail",
    ),
    path(
        "counter_reading/update/<int:pk>/",
        CounterReadingUpdateView.as_view(),
        name="counter_reading_update",
    ),
    path(
        "counter_reading/delete/<int:pk>/",
        CounterReadingDeleteView.as_view(),
        name="counter_reading_delete",
    ),
    path("receipts/list/", ReceiptListView.as_view(), name="receipt_list"),
    path(
        "receipt/detail/<int:pk>/", ReceiptDetailView.as_view(), name="receipt_detail"
    ),
    path("receipt/create/", ReceiptCreateView.as_view(), name="receipt_create"),
    path(
        "receipts/update/<int:pk>/", ReceiptUpdateView.as_view(), name="receipt_update"
    ),
    path(
        "receipts/delete/<int:pk>/", ReceiptDeleteView.as_view(), name="receipt_delete"
    ),
    path("send_user_invite/<int:pk>/", send_user_invite, name="user_invite"),
    path("cashbox/", CashBoxListView.as_view(), name="cashbox_list"),
    path(
        "cashbox/income/create/",
        CashBoxIncomeCreateView.as_view(),
        name="cashbox_income_create",
    ),
    path(
        "cashbox/expense/create/",
        CashBoxExpenseCreateView.as_view(),
        name="cashbox_expense_create",
    ),
    path(
        "cashbox/<int:pk>/update/", CashBoxUpdateView.as_view(), name="cashbox_update"
    ),
    path(
        "cashbox/<int:pk>/delete/", CashBoxDeleteView.as_view(), name="cashbox_delete"
    ),
    path(
        "call-requests/create/",
        CallMasterCreateView.as_view(),
        name="callmaster_create",
    ),
    path("call-requests/", CallMasterListView.as_view(), name="callmaster_list"),
    path(
        "call-requests/<int:pk>/update/",
        CallMasterUpdateView.as_view(),
        name="callmaster_update",
    ),
    path(
        "call-requests/<int:pk>/delete/",
        CallMasterDeleteView.as_view(),
        name="callmaster_delete",
    ),
    path(
        "call-requests/<int:pk>/",
        CallMasterDetailView.as_view(),
        name="callmaster_detail",
    ),
    path("messages/", MessageListView.as_view(), name="message_list"),
    path("messages/create/", MessageCreateView.as_view(), name="message_create"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path(
        "messages/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path(
        "cashbox/export/excel/",
        CashboxExportExcelView.as_view(),
        name="cashbox_export_excel",
    ),
    path("receipt/<int:pk>/copy/", ReceiptCopyView.as_view(), name="receipt_copy"),
    path("receipt/<int:pk>/pdf/", ReceiptPDFView.as_view(), name="receipt_pdf"),
    path(
        "account/export/excel/",
        PersonalAccountExportExcelView.as_view(),
        name="account_export_excel",
    ),
    path("owners/create/", OwnerCreateView.as_view(), name="owner_create"),
]
