from django.urls import path

from .views import (
    AboutUsPageView,
    AccountCreateView,
    AccountDeleteView,
    AccountDetailView,
    AccountListView,
    AccountUpdateView,
    ApartmentCreateView,
    ApartmentDeleteView,
    ApartmentDetailView,
    ApartmentListView,
    ApartmentUpdateView,
    ContactPageView,
    CreateArticleView,
    DeleteArticleView,
    EditArticleView,
    HouseDeleteView,
    HouseDetailView,
    HouseListView,
    HouseView,
    ListArticleView,
    MainPageView,
    OwnerListView,
    PaymentDetailView,
    RolesUpdateView,
    ServiceEditView,
    ServicePageView,
    StatisticPageView,
    TariffDetailView,
    TariffListView,
    UserCreateView,
    UserDeleteView,
    UserDetailView,
    UserEditView,
    UserListView,
    UserProfileView,
    get_owner_by_apartment,
    get_sections_and_floors,
    get_service_unit,
    get_user_role,
    send_user_invite,
    tariff_update,
)

app_name = "adminlte"

urlpatterns = [
    path("", StatisticPageView.as_view(), name="statistic"),
    path("managesite/mainpage", MainPageView.as_view(), name="edit_main_page"),
    path("managesite/aboutus", AboutUsPageView.as_view(), name="edit_about_us_page"),
    path("managesite/services", ServicePageView.as_view(), name="edit_service_page"),
    path("managesite/contacts", ContactPageView.as_view(), name="contacts_edit"),
    path("settings/", RolesUpdateView.as_view(), name="roles_update"),
    path("user/edit/<int:pk>", UserEditView.as_view(), name="user_edit"),
    path("user/create/", UserCreateView.as_view(), name="user_create"),
    path("user/list/", UserListView.as_view(), name="users_list"),
    path("user/profile", UserProfileView.as_view(), name="user_profile"),
    path("user/detail/<int:pk>", UserDetailView.as_view(), name="user_detail"),
    path("user/delete/<int:pk>", UserDeleteView.as_view(), name="user_delete"),
    path("user/invite/<int:pk>", send_user_invite, name="user_invite"),
    path("service/edit/", ServiceEditView.as_view(), name="service_edit"),
    path("tariff/list/", TariffListView.as_view(), name="tariff_list"),
    path("tariff/create/", tariff_update, name="tariff_create"),
    path("tariff/edit/<int:pk>", tariff_update, name="tariff_update"),
    path("tariff/getservice/", get_service_unit, name="get_service_unit"),
    path("tariff/detail/<int:pk>", TariffDetailView.as_view(), name="tariff_detail"),
    path("payment/detail/", PaymentDetailView.as_view(), name="payment_detail"),
    path("article/list/", ListArticleView.as_view(), name="article_list"),
    path("article/edit/<int:pk>", EditArticleView.as_view(), name="article_edit"),
    path("article/create/", CreateArticleView.as_view(), name="article_create"),
    path("article/delete/<int:pk>", DeleteArticleView.as_view(), name="article_delete"),
    path("house/list/", HouseListView.as_view(), name="house_list"),
    path("house/detail/<int:pk>/", HouseDetailView.as_view(), name="house_detail"),
    path("house/create/", HouseView.as_view(), name="house_create"),
    path("house/edit/<int:pk>/", HouseView.as_view(), name="house_update"),
    path("house/delete/<int:pk>/", HouseDeleteView.as_view(), name="house_delete"),
    path("house/get-user-role/", get_user_role, name="get_user_role"),
    path("apartment/list/", ApartmentListView.as_view(), name="apartment_list"),
    path("apartment/create/", ApartmentCreateView.as_view(), name="apartment_create"),
    path(
        "aparment/edit/<int:pk>/",
        ApartmentUpdateView.as_view(),
        name="apartment_update",
    ),
    path(
        "apartment/delete/<int:pk>/",
        ApartmentDeleteView.as_view(),
        name="apartment_delete",
    ),
    path(
        "apartment/detail/<int:pk>/",
        ApartmentDetailView.as_view(),
        name="apartment_detail",
    ),
    path(
        "apartment/getsecandfloor/",
        get_sections_and_floors,
        name="get_sections_and_floors",
    ),
    path("owners/", OwnerListView.as_view(), name="owners_list"),
    path("accounts/create/", AccountCreateView.as_view(), name="account_create"),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "get_owner_by_apartment/", get_owner_by_apartment, name="get_owner_by_apartment"
    ),
    path("accounts/<int:pk>/", AccountDetailView.as_view(), name="account_detail"),
    path(
        "accounts/<int:pk>/update/", AccountUpdateView.as_view(), name="account_update"
    ),
    path(
        "accounts/<int:pk>/delete/", AccountDeleteView.as_view(), name="account_delete"
    ),
]
