# Generated by Django 6.0.2 on 2026-02-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("house", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="callmaster",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.apartments"
            ),
        ),
    ]
