# Generated by Django 6.0.2 on 2026-02-18 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0002_initial"),
        ("house", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="callmaster",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="callmaster",
            name="master_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.roles"
            ),
        ),
        migrations.AddField(
            model_name="cashbox",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.article"
            ),
        ),
        migrations.AddField(
            model_name="counter",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.apartments"
            ),
        ),
        migrations.AddField(
            model_name="counterreadings",
            name="counter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.counter"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_message",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_message",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashbox",
            name="personal_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.personalaccount"
            ),
        ),
        migrations.AddField(
            model_name="receipts",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.apartments"
            ),
        ),
        migrations.AddField(
            model_name="cashbox",
            name="receipts",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.receipts"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="measure",
            field=models.ManyToManyField(to="crm.measure"),
        ),
        migrations.AddField(
            model_name="counter",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.service"
            ),
        ),
        migrations.AddField(
            model_name="servicereceipts",
            name="counter_reading",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.counterreadings"
            ),
        ),
        migrations.AddField(
            model_name="receipts",
            name="service_receipt",
            field=models.ManyToManyField(to="crm.servicereceipts"),
        ),
        migrations.AddField(
            model_name="tariffservice",
            name="currency",
            field=models.ManyToManyField(to="crm.currency"),
        ),
        migrations.AddField(
            model_name="tariffservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.service"
            ),
        ),
        migrations.AddField(
            model_name="tariffservice",
            name="tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.tariffs"
            ),
        ),
        migrations.AddField(
            model_name="servicereceipts",
            name="tariff_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.tariffservice"
            ),
        ),
    ]
