# Generated by Django 6.0.2 on 2026-04-11 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0002_initial"),
        ("house", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="callmaster",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="callmaster",
            name="master_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.roles"
            ),
        ),
        migrations.AddField(
            model_name="cashbox",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.article",
                verbose_name="Стаття",
            ),
        ),
        migrations.AddField(
            model_name="cashbox",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AddField(
            model_name="counterreadings",
            name="apartment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="house.apartment",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Одержувач",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Відправник",
            ),
        ),
        migrations.AddField(
            model_name="cashbox",
            name="personal_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cashbox_records",
                to="crm.personalaccount",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="house.apartment",
                verbose_name="Квартира",
            ),
        ),
        migrations.AddField(
            model_name="cashbox",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cashbox_records",
                to="crm.receipt",
            ),
        ),
        migrations.AddField(
            model_name="receiptitem",
            name="counter_reading",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.counterreadings",
            ),
        ),
        migrations.AddField(
            model_name="receiptitem",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="crm.receipt",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.currency",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.measure",
            ),
        ),
        migrations.AddField(
            model_name="receiptitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.service"
            ),
        ),
        migrations.AddField(
            model_name="counterreadings",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="crm.service",
            ),
        ),
        migrations.AddField(
            model_name="tariffs",
            name="services",
            field=models.ManyToManyField(blank=True, null=True, to="crm.service"),
        ),
        migrations.AddField(
            model_name="receipt",
            name="tariff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.tariffs",
                verbose_name="Тариф",
            ),
        ),
        migrations.AddField(
            model_name="tariffservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.service"
            ),
        ),
        migrations.AddField(
            model_name="tariffservice",
            name="tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.tariffs"
            ),
        ),
    ]
