# Generated by Django 6.0.2 on 2026-04-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashbox",
            options={"ordering": ["-id"]},
        ),
    ]
