# Generated by Django 6.0.2 on 2026-04-13 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_cashbox_options"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="callmaster",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="callmaster",
            name="master_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="user.roles"
            ),
        ),
        migrations.AlterField(
            model_name="counterreadings",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="readings",
                to="crm.service",
            ),
        ),
        migrations.AlterField(
            model_name="tariffservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.service"
            ),
        ),
        migrations.AlterField(
            model_name="tariffservice",
            name="tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.tariffs"
            ),
        ),
    ]
