# Generated by Django 6.0.2 on 2026-02-18 17:05

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image1", models.ImageField(upload_to="images/")),
                ("image2", models.ImageField(upload_to="images/")),
                ("image3", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="ContactsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="InfoItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="SeoBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("keywords", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.banners",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.contactspage",
                    ),
                ),
                (
                    "info_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.infoitems",
                    ),
                ),
                (
                    "seo_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.seoblock",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contactspage",
            name="seo_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.seoblock"
            ),
        ),
        migrations.CreateModel(
            name="AboutUsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("director_photo", models.ImageField(upload_to="images/")),
                ("additional_title", models.CharField(max_length=100)),
                ("additional_description", models.TextField()),
                (
                    "additional_gallery",
                    models.ManyToManyField(
                        related_name="about_us_additional_gallery", to="website.gallery"
                    ),
                ),
                (
                    "gallery",
                    models.ManyToManyField(
                        related_name="about_us_main_gallery", to="website.gallery"
                    ),
                ),
                (
                    "seo_bloc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.seoblock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.seoblock",
                    ),
                ),
                ("service", models.ManyToManyField(to="website.infoitems")),
            ],
        ),
    ]
