# Generated by Django 6.0.2 on 2026-04-11 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0003_initial"),
        ("house", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.tariffs",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="floor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="house.floor",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="floor",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.house"
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.house"
            ),
        ),
        migrations.AddField(
            model_name="houseuser",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.house"
            ),
        ),
        migrations.AddField(
            model_name="houseuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.house"
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="house.section",
            ),
        ),
    ]
