# Generated by Django 6.0.2 on 2026-02-18 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0003_initial"),
        ("house", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apartments",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="apartments",
            name="tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.tariffs"
            ),
        ),
        migrations.AddField(
            model_name="apartments",
            name="floor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.floor"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="floor",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.house"
            ),
        ),
        migrations.AddField(
            model_name="apartments",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.house"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.house"
            ),
        ),
        migrations.AddField(
            model_name="apartments",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.section"
            ),
        ),
    ]
